ddev/ddev-addon-template

.github/workflows/tests.yml, README.md, docker-compose.addon-template.yaml, install.yaml
DDEV now requires #ddev-generated in a target file to overwrite it. Minor other changes
=> Update with #ddev-generated

.github/workflows/tests.yml
* https://github.com/actions/runner-images/issues/6283
brew is no longer in default $PATH
=> Update brew path as no longer provided in image

.github/workflows/tests.yml
Running tests in my project, I get this notice:
```
[tests (stable)](https://github.com/paul-m/ddev-drupal-core/actions/runs/3406171221/jobs/5664672705)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
```
Updating [actions/checkout](https://github.com/actions/checkout) to v3 solves this.
=> Update actions/checkout to v3

.github/workflows/tests.yml
We've had loads of rate limiting problems with ddev get in these tests. See if we can populate DDEV_GITHUB_TOKEN to prevent it.
=> Use github token to prevent rate limiting

README.md, tests/test.bats
This changes references to drud to "ddev".
Remaining work:
=> First round of drud->ddev changes

README.md, install.yaml
As of DDEV v1.21.4+, it's best for add-ons that use pre_install or post_install_actions to have `#ddev-description` in each action to say what they are doing.
Add that info.
=> Add info about #ddev-description annotation

.github/workflows/tests.yml
Hi,
if we use the `workflow_dispatch` to launch the "tests" action, the `tmate debugging session` step runs even if we let the default `debug_enabled` input to `false`.
This PR fixes it and runs the `tmate debugging session` step only if the value of `debug_enabled` has been explicitly set to `true`.
=> Run tmate debugging session only if workflow_dispatch debug_enabled is true

README.md
This PR fixes the missing "." in the docs for a suggested filename.
=> [docs] fix typo in suggested filename

tests/test.bats
Now, regarding to the template file, we have to write checks twice: 
- In `@test "install from directory"`
- And in `@test "install from release"` - the same lines.
Will be good to move that to a separate function, to not have two places to manage them. 
So, I've created a function `health_checks()` that contains only a single instance of checks.
And have moved it to the top, because it will be edited more frequiently, than test functions.
=> Move health checks to a separate function in bats test file

.github/workflows/tests.yml
This PR resolves a "unable to access" error message during action tests. 
See gautamkrishnar/keepalive-workflow#14
=> 🔓 update Github workflow permission

.github/workflows/tests.yml
Lots of problems with homebrew git clone failing, for example https://github.com/ddev/ddev-mongo/actions/runs/5462288647/jobs/9941441600
Try removing HOMEBREW_NO_INSTALL_FROM_API (DDEV only wanted it for the `brew install --HEAD` feature)
@Bo98 was kind enough to correspond via email to suggest this technique, which ought to work on linux/GitHub Actions
Related issues:
* https://github.com/Homebrew/homebrew-core/issues/135315
* https://github.com/Homebrew/homebrew-cask/issues/150323#issuecomment-1621758162
* https://github.com/Homebrew/brew/issues/15621#issuecomment-1620839202
/cc @tyler36
=> Remove HOMEBREW_NO_INSTALL_FROM_API

.github/workflows/tests.yml, README.md
We now have the lovely [github-action-add-on-test](https://github.com/ddev/github-action-add-on-test) from @julienloizelet - THANKS!
This uses it.
=> ci: use github action for bulk of github test

install.yaml
* #35
The README instructions say to replace 'addon-template' with your add-on name, but this string doesn't fit the pattern.
Changes the placeholder so it matches the others.
=> docs: change sample name of add-on so it matches README instructions, fixes #35

install.yaml
There is an example of every section _except_ `dependencies`. If you're like me, that might cause you to miss it.
Adds an commented-out example
https://discord.com/channels/664580571770388500/1184888354886647878
=> Include dependencies example in template

README.md
README.md:
- some links are broken
- it is unclear how to add a GitHub topic (also the word used here is "label" which is not in GitHub docs)
- there is no link how to create a GitHub release
- some DDEV references use lowercase letters
- some sentences can be simplified
Fixes the above.
=> Reformatting, paraphrasing, and adding additional links to GitHub docs

docker-compose.addon-template.yaml
All services should mount ddev-global-cache. This becomes more important with 
* https://github.com/ddev/ddev/pull/5753
=> All services should mount ddev-global-cache

.github/workflows/tests.yml
This PR bumps "github-action-add-on-test" to `v2`.
This resolves the dummy commit made by "keepalive-workflow".
=> ⏫ bump "github-action-add-on-test"

.github/workflows/tests.yml
Recently I was updating the tyler36/ddev-laravel-queue addon.
The tests generally take 5-6 minutes.
When I push a new commit, it triggers another workflow process. 
At one point, I click a couple of "Commit suggestion"s and I had 6 workflows running on the same branch!
This PR configures "concurrency"  in the workflow. This _could_ be set on a per-job level, but I opted for the entire workflow with this PR. Feel free to change this is desired.
Concurrency is set to cancel in-progress workflows on a branch/tag before starting a new workflow on the same branch/tag.
See https://docs.github.com/en/actions/using-jobs/using-concurrency
=> Prevent concurrent workflows

install.yaml
* A couple of add-ons have inadvertently used directories in the install.yaml, and shared directories, like `commands`. Thix can lead to `ddev get --remove` removing the whole directory. 
* Not all systems have the `arch` command, use `uname -m` in the example instead.
Don't give the bad example.
=> docs: Don't show bad examples in install.yaml

install.yaml
- https://github.com/ddev/ddev/pull/6433
- https://github.com/ddev/ddev/issues/5969
- Adds `ddev_version_constraint`.
- Removes `#ddev-nodisplay`.
See instructions from https://github.com/ddev/ddev/pull/6433
=> feat: add `ddev_version_constraint` (available since DDEV v1.23.4), remove `#ddev-nodisplay`

README.md, docker-compose.addon-template.yaml, install.yaml
This was meant to be the same as:
- https://github.com/ddev/ddev/pull/6514
But I reviewed the files, and made more changes.
- updates the link to the example file for complex `install.yaml`
- uses stable docs instead of latest
- removes unnecessary stanza `networks: [default, ddev_default]`
- updates the contributor training links for add-ons .
=> refactor: update old links

tests/test.bats
Out of the box, addon tests fail if there are no releases. This can trip up addon developers who are unaware of this workflow, or submit PRs that try to fix issue in the current release
https://github.com/ddev/github-action-add-on-test/34 adds the ability to skip tests tagged with "release".
This PR adds this to the appropriate test.
=> add "release" tag to release test

README.md, README_DEBUG.md
I've started dropping this section from addons I create because adds noise to the main readme.
Extracts information to a seperate file, `README_DEBUG.md`
Updates TOC link to `README_DEBUG.md`.
The idea here is we still want to keep the debug information present and available, but not overwhelm addon user with addon developer technical details.
=> extract debug info

README.md
It says in the README: 
> 12. Update the `README.md` header in Title Case format, for example, use `# DDEV Redis`, not `# ddev-redis`.
the README itself should follow that advice as well :)
Updates the title of the header to use Title Case.
=> docs: update README.md to align with the style in the README

.github/PULL_REQUEST_TEMPLATE.md, install.yaml
We want users to have DDEV v1.24.3+ (for Mutagen fix https://ddev.com/blog/open-source-for-the-win/#mutagen-problemreport)
Pull template can include a template for tarball install (I always forget the exact URL)
Updates the mentioned files.
=> refactor: use v1.24.3 constraint, update pull template

README.md
Maintained badge required manual update from time to time.
- Makes `tests` badge show status for the main branch only.
- Uses https://shields.io/badges/git-hub-last-commit-branch instead of the `project is maintained` badge.
- Adds `release` badge.
https://github.com/ddev/ddev-addon-template/blob/20250410_stasadev_badges/README.md
=> feat: update badges, replace maintained badge with last commit

.github/workflows/tests.yml
actions:write permission was only required for the recently removed `gautamkrishnar/keepalive-workflow` action
Set `contents: read`  as default permission
It can be tested on any repository that uses the `ddev/github-action-add-on-test`
=> feat(tests workflow): Downgrade permissions to contents:read

.github/workflows/tests.yml, tests/test.bats
Allow bats runners to avoid deletion of the testdir. Helpful when uploading artifacts as per
- https://github.com/ddev/github-action-add-on-test/pull/50
Detect GITHUB_ENV env variable and avoid deleting the test directory. This is set to true for runs in Github Actions. Locally you can set it as well for same behavior.
```bash
ddev add-on get https://github.com/ddev/ddev-addon-template/tarball/refs/pull/79
ddev restart
```
=> Preserve TESTDIR when using Github Actions

tests/test.bats
- For #79
I noticed that when you have several tests, and store `TESTDIR` to `GITHUB_ENV`, you end up with this in GITHUB_ENV:
```
...
TESTDIR=/home/runner/tmp/test-ddev-addon-template.YVvnDD
TESTDIR=/home/runner/tmp/test-ddev-addon-template.TtvrpK
```
In result only the last TESTDIR is used for uploading artifacts.
TESTDIR is `~/tmp/${PROJNAME}.XXXXXX)`
It's better to store TESTDIR as `~/tmp/${PROJNAME}`, so people can use glob `${TESTDIR}*/path/to/files` to store all test results.
Also I added a check `[ -e "${GITHUB_ENV:-}" ]` (because we don't want to write to some random files locally when using `GITHUB_ENV=1 bats tests`
=> fix: store TESTDIR without suffix, for #79

install.yaml
Duplicate of #77 - I cleaned up a lot of my repos and accidentally deleted  this fork that closed the PR. I couldn't find a way to re-open that one.
---
I was trying this with a local compiled version of ddev and obviously I wanted that binary to be used for ddev commands instead of the globally installed one. 
I think this is a nice tweak to have in the template so that it's easier to find.
Probably worth adding it to the docs as well.
=> refactor: improve install.yaml examples

.github/scripts/update-checker.sh, README.md
Some DDEV add-ons can't work [offline](https://ddev.readthedocs.io/en/stable/users/usage/offline/) because the base image for them is not pulled:
- `ddev/ddev-drupal-solr`
- `ddev/ddev-opensearch`
- `ddev/ddev-solr`
- `stasadev/ddev-frankenphp`
To reproduce:
```
$ docker image rm solr:9.6
$ ddev add-on get ddev/ddev-solr && ddev start && ddev poweroff
$ ddev start
...
', stderr='failed to solve: solr:9.6: failed to resolve source metadata for docker.io/library/solr:9.6: failed to do request: Head "https://registry-1.docker.io/v2/library/solr/manifests/9.6": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution' 
```
But if you already have the `solr:9.6` image pulled, there will be no error.
Adds check for `build:` + `image:`
DDEV has logic to pull images for `web` …
=> feat: add check for `build:` with `image:` in `docker-compose.*.yaml` to use DDEV offline

.gitattributes, .github/scripts/update-checker.sh
Releases by default container everything. But they sure don't need the tests
* Add .gitattributes to exclude tests
* Add .gitattributes testing to the update checker.
=> fix: Exclude tests from release tarball
